# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    # - forward_position_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - link2_to_link1
      - link3_to_link2
      - link4_to_link3
      - link5_to_link4
      - link6_to_link5
      - link6output_to_link6
    action_ns: "follow_joint_trajectory"
    default: true

  # forward_position_controller:
  #   type: FollowJointTrajectory
  #   joints:
  #     - link2_to_link1
  #     - link3_to_link2
  #     - link4_to_link3
  #     - link5_to_link4
  #     - link6_to_link5
  #     - link6output_to_link6
  #   action_ns: "follow_joint_trajectory"
  #   default: true