# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 40  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - link2_to_link1
      - link3_to_link2
      - link4_to_link3
      - link5_to_link4
      - link6_to_link5
      - link6output_to_link6
    command_interfaces:
      - position
    state_interfaces:
      - position
    allow_nonzero_velocity_at_trajectory_end: true

forward_position_controller:
  ros__parameters:
    joints:
      - link2_to_link1
      - link3_to_link2
      - link4_to_link3
      - link5_to_link4
      - link6_to_link5
      - link6output_to_link6