/**:
    ros__parameters:
      video_device: "/dev/video0"  # USB camera device
      framerate: 30.0
      io_method: "mmap"
      frame_id: "jetcocam"
      pixel_format: "mjpeg2rgb"  # see usb_cam/supported>
      av_device_format: "RGB24"
      image_width: 1920
      image_height: 1080
      camera_name: "test_camera"
      # camera_info_url: "package://usb_cam/config/ca>
      camera_info_url: "package://jetcobot_bringup/config/jetcocam_1_calib.yaml"
      brightness: -1
      contrast: -1
      saturation: -1
      sharpness: -1
      gain: -1
      auto_white_balance: true
      white_balance: 4000
      autoexposure: true
      exposure: 100
      autofocus: false
      focus: -1